### ISSUE TITLE
"desired_linear_velocity" parameter is not working

### ISSUE THREAD

**Issue by YoungRicky7** [blackcoffeerobotics/vector_pursuit_controller#7]
ROS version humble
gazebo version: classic 11
I ran the controller in the gazebo,and set "desired_linear_velocity" to 2.0,while the simulation is running, I use "ros2 topic echo /cmd_vel" to check the speed of the robot,however it showed 0.26 instead of 2.0. I also tried set "min_x_velocity_threshold" bigger than 0.26, but it's not working either

**Comment by exMachina316** [comment]
Hey @YoungRicky7!! Could you share the costmap snapshot in rviz to get a better understanding of the enviornmet. I think the controller may slowing down due to costmap scaling. To rule it out you can set `use_cost_regulated_linear_velocity_scaling` in the config file to `false`.

Example config file:
```yaml
FollowPath:
      # Changes
      use_cost_regulated_linear_velocity_scaling: false
      cost_scaling_dist: 0.5
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0
      # Rest of the params
```
